#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'husky post-merge script'

if  [ -e ../pnpm-lock.yaml ]; then
  pnpm i
elif [ -e ../package-lock.json ]; then
  npm i
elif [ -e ../yarn.lock ]; then
  yarn
fi